//JSON data
var json = {'Events':[
['1':['name':'Natural Discourse','date':'Monday, December 03rd, 2012','description':'The UC Botanical Garden presents Natural Discourse: artists, architects, scientists & poets in the Garden is a collaborative project between the University of  California Botanical Garden at Berkeley and a multidisciplinary group of artists, writers, architects and researchers who have been invited to spend time in the Garden's extraordinary collection of plants, engage with the horticulture and develop new site specific work. Curated by Mary Ann Friel and Shirley Watts.

Off—site Installations: BART Rotunda installation by Deborah O'Grady in Downtown Berkeley at Center Street and Shattuck Avenue. Billboard installation by Michell Maher in Berkeley and San Francisco.

Opening Day:  Meet the Artists & Curators:  10:00 am—4:00 pm.']],
['2':['name':'The Art of Fumiyo Yoshikawa','date':'Monday, December 03rd, 2012','description':'The Berkeley Public Library is happy to display paintings by Bay Area artist, Fumiyo Yoshikawa. A native of Japan, Yohikawa uses traditional nihonga and sumi—e Japanese methods of ink painting originating in China with with a spiritual basis in Zen Buddihism. This form of expressing nature's colors through shades of black ink has been popular in China, Korea and Japan for many centuries. Yoshikawa continues to explore these traditional techniques in her contemporary abstract and figurative paintings on display in the exhibition. 

All are invited to meet Fumiyo Yoshikawa and discuss her work during a FREE artist's reception on Sun. Nov. 11th at 2:00 pm.

Access to the exhibit is available during the library's open hours: Mon. 12:00—8:00 pm; Tue. 10:00 am—8:00 pm; Wed.—Sat. 10:00 am—6:00 pm; Sun. 1:00—5:00 pm.']],
['3':['name':'Before California','date':'Monday, December 03rd, 2012','description':'What was California like centuries ago, before we entered the mix? Which ecological processes did our presence interrupt? What became of the wildlife that once roamed free? Artist, scientist and celebrated pioneer of historical ecology Laura Cunningham has spent a large part of her career attempting to answer these puzzling questions. The result is a striking array of illustrations, sketches, and murals that will be featured in Cunningham’s first solo exhibition at the David Brower Center.

Gallery Hours:  Mon.—Fri. 10:00 am—5:00 pm; Sun. 10:00 am—1:00 pm.']],
['4':['name':'Fiat Lux Redux:  Ansel Adams & Clark Kerr','date':'Monday, December 03rd, 2012','description':'Featuring original prints by legendary photographer Ansel Adams, this is an exhibition of rarely—seen images of the University of California System in the 1960s. The images, commissioned by former UC President Clark Kerr, and published in the 1967 book Fiat Lux which celebrated the educational system's centennial, offer a rarely seen look at the evolution of the renowned University of California system through the eye of a master photographer best known for his iconic California landscapes. The exhibition also showcases related archival materials about the controversial Kerr himself, and the evolution of his ideas and ideals.']],
['5':['name':'Space Junk 3—D Film','date':'Monday, December 03rd, 2012','description':'Space Junk 3—D is an award—winning film. Take a trip to outer space to learn more about the space junk collisions in Earth's orbit. See the satellites that make modern life possible. Experience mind—boggling collisions, both natural and man—made. Soar from the stunning depths of Meteor Crater to an unprecedented view of our increasingly crowded orbits——22,000 miles above earth. Join us as foremost expert Don Kessler, the 'Father of Space Junk,' guides us through the challenges we face in protecting them, forging a new age of space discovery. Showtimes:  10:45 am, 11:15 am, 11:45 am, 12:15 pm, 12:45 pm and 1:15 pm.']],
['6':['name':'The Last Reef 3—D','date':'Monday, December 03rd, 2012','description':'Go on a thrilling underwater journey and explore the beauty and mysteries of a reef ecosystem. Fly across iridescent tropical corals, brush through millions of jellyfish, and visit a world where the closer you look, the more you see in these living underwater cities.

made with new macro—underwater cinematography, The Last Reef reveals an astonishing world rarely seen at this scale. From surprisingly colorful wormlike nudbranchs no bigger than you little finger, to  giant clams, anemones, and 'Christmas tree' worms, the film presents an unprecedented vision of the intriguing creatures that participate in altering the geology of our planet.  Showtimes:  10:45 am, 11:15 am, 11:45 am, 12:15 pm, and 1:15 pm.']],
['7':['name':'Planetarium @ Lawrence Hall of Science','date':'Monday, December 03rd, 2012','description':'Explore the skies in our interactive Planetarium!. Our geodesic dome is installed with a single fish—eye digital full—dome projection system. The45—seat Planetarium is wheelchair accessible. Presented every Saturday and Sunday, plus most holidays. Daily programs are also offered Monday—Friday during the summer and during special holiday weeks. Programs are approximately 40 minutes, and are presented with live activities. Questions are encouraged!

1:00 pm — A Sky Full of Stars (ages 4—8 with adult); 2:00 pm — Constellations Tonight (ages 6—8 to adult); 3:00 pm — Native American Astronomy (ages 8 to adult).']],
['8':['name':'Mostly Mends: Repaired & Repurposed, exhibit','date':'Monday, December 03rd, 2012','description':'For more than 20 of the Gallery's 40 plus years, we have been extolling the glory of 'mends', those well—worn, even broken objects that have been skillfully repaired. It is often an adroit mend that makes something precious out of an otherwise commonplace piece. In this exhibit, we again pay tribute to both the artistry and creativity shown by the repairs, as well as to the beauty of the imperfection. The ingenuity and frugality that are the hallmarks of this exhibit should provide inspiration for those of us who may have grown up in a disposable society.

Gallery Hours:  Mon.—Fri. 10:30 am—2:00 pm, or by chance or appointment.']],
['9':['name':'The Asuit Cloth (On—going Exhibit)','date':'Monday, December 03rd, 2012','description':'There is little known as to the origins of this magical shimmering cloth, and no common agreement as to its spelling (Assuit, Asute, Azute), but it is commonly agreed to originate in the Egyptian town of Asyut where is also referred to as Tulle be Telli, the Egyptian name for 'net of metal.'

Discovering Asuit cloths can be a mesmerizing experience. There is a magic in these shawls as if some secret code is embedded in the patters, which at first seem regular and repetitive and then to notice all the subtle variations and the wonder whether this was intentional, away to identify the maker, or simply a reflection of the skill or lack of skill, of the maker. The patterns only seem to repeat and perhaps the theory that these were created by blind workers has a basis.']],
['10':['name':'The Textile Treasures of LMLT','date':'Monday, December 03rd, 2012','description':'A reflection of the richness, versatility and human spirit as expressed through the work of our hands across all cultures and time. some treasures are obvious, those that were created in a world inconceivable to us today. Work beyond the limits of any hand skill we can conceive of...some are less obvious, experiments with fibers to simply test our skills and create beauty that gives us joy...some that express a connection to other worlds of beasts and gods that we honor...some simply a test of endurance...and some a dedication of love.']],
['11':['name':'Science On a Sphere (SOS)','date':'Monday, December 03rd, 2012','description':'SOS creates stunning visual effects from real scientific data, and displays them dynamically on a six—foot—diameter globe. Visitors can watch the expanding wave pattern of a devastating tsunami, massive storms forming and moving over Earth's oceans and landmasses, nigh lights around the globe that reveal our planet's most densely populated areas, and more. Science On a Sphere was developed by Researchers at the national Oceanic and Atmospheric Administration (NOAA).

The Lawrence Hall of Science is open daily. Closed Thanksgiving and Christmas.']],
['12':['name':' MATRIX 244, Trimpin: Nancarrow Percussion Orchestra','date':'Monday, December 03rd, 2012','description':'MATRIX 244 introduces a new sculptural sound installation by the internationally acclaimed Seattle—based artist Trimpin, whose work is foremost about visualizing sound.

Gallery Admission: Free: BAM/PFA members, UC students/faculty/staff, 12 & under; $$10 General, $$7 non—UC students, 65+, disabled persons, ages 13—17']],
['13':['name':'Jazzschool Vocal Program:  Sheila Jordan','date':'Monday, December 03rd, 2012','description':'The Jazzschool Vocal Program presents: Sheila Jordan at the Freight & Salvage. The Lifer and Music of NEA Jazz Master. Today, at the age of 83, Sheila continues to travel the world singing, teaching and sharing the deep spirit and soul that is jazz. The evening will feature appearances Laurie Antonioli, Madeline Eastman, Kitty Margolis, Ed Reed, and Sheila Jordan herself.']],
['14':['name':'Hear Me Now, cell phone monologues','date':'Monday, December 03rd, 2012','description':'A First Person Singular Original. From the checkout line to the seat behind you on the train, the modern phenomenon of the cell phone monologue is often a deliberate display, a defiant assertion of self. We're calling on the best and brightest Bay Area talent to put this unsolicited public theater into a proper context, and demonstrate what iPhone exhibitionism can inadvertently, and entertainingly, reveal.

Easy street parking. Across from Ashby BART station.

']],
['15':['name':'Natural Discourse','date':'Tuesday, December 04th, 2012','description':'The UC Botanical Garden presents Natural Discourse: artists, architects, scientists & poets in the Garden is a collaborative project between the University of  California Botanical Garden at Berkeley and a multidisciplinary group of artists, writers, architects and researchers who have been invited to spend time in the Garden's extraordinary collection of plants, engage with the horticulture and develop new site specific work. Curated by Mary Ann Friel and Shirley Watts.

Off—site Installations: BART Rotunda installation by Deborah O'Grady in Downtown Berkeley at Center Street and Shattuck Avenue. Billboard installation by Michell Maher in Berkeley and San Francisco.

Opening Day:  Meet the Artists & Curators:  10:00 am—4:00 pm.']],
['16':['name':'The Art of Fumiyo Yoshikawa','date':'Tuesday, December 04th, 2012','description':'The Berkeley Public Library is happy to display paintings by Bay Area artist, Fumiyo Yoshikawa. A native of Japan, Yohikawa uses traditional nihonga and sumi—e Japanese methods of ink painting originating in China with with a spiritual basis in Zen Buddihism. This form of expressing nature's colors through shades of black ink has been popular in China, Korea and Japan for many centuries. Yoshikawa continues to explore these traditional techniques in her contemporary abstract and figurative paintings on display in the exhibition. 

All are invited to meet Fumiyo Yoshikawa and discuss her work during a FREE artist's reception on Sun. Nov. 11th at 2:00 pm.

Access to the exhibit is available during the library's open hours: Mon. 12:00—8:00 pm; Tue. 10:00 am—8:00 pm; Wed.—Sat. 10:00 am—6:00 pm; Sun. 1:00—5:00 pm.']],
['17':['name':'Before California','date':'Tuesday, December 04th, 2012','description':'What was California like centuries ago, before we entered the mix? Which ecological processes did our presence interrupt? What became of the wildlife that once roamed free? Artist, scientist and celebrated pioneer of historical ecology Laura Cunningham has spent a large part of her career attempting to answer these puzzling questions. The result is a striking array of illustrations, sketches, and murals that will be featured in Cunningham’s first solo exhibition at the David Brower Center.

Gallery Hours:  Mon.—Fri. 10:00 am—5:00 pm; Sun. 10:00 am—1:00 pm.']],
['18':['name':'Fiat Lux Redux:  Ansel Adams & Clark Kerr','date':'Tuesday, December 04th, 2012','description':'Featuring original prints by legendary photographer Ansel Adams, this is an exhibition of rarely—seen images of the University of California System in the 1960s. The images, commissioned by former UC President Clark Kerr, and published in the 1967 book Fiat Lux which celebrated the educational system's centennial, offer a rarely seen look at the evolution of the renowned University of California system through the eye of a master photographer best known for his iconic California landscapes. The exhibition also showcases related archival materials about the controversial Kerr himself, and the evolution of his ideas and ideals.']],
['19':['name':'Space Junk 3—D Film','date':'Tuesday, December 04th, 2012','description':'Space Junk 3—D is an award—winning film. Take a trip to outer space to learn more about the space junk collisions in Earth's orbit. See the satellites that make modern life possible. Experience mind—boggling collisions, both natural and man—made. Soar from the stunning depths of Meteor Crater to an unprecedented view of our increasingly crowded orbits——22,000 miles above earth. Join us as foremost expert Don Kessler, the 'Father of Space Junk,' guides us through the challenges we face in protecting them, forging a new age of space discovery. Showtimes:  10:45 am, 11:15 am, 11:45 am, 12:15 pm, 12:45 pm and 1:15 pm.']],
['20':['name':'The Last Reef 3—D','date':'Tuesday, December 04th, 2012','description':'Go on a thrilling underwater journey and explore the beauty and mysteries of a reef ecosystem. Fly across iridescent tropical corals, brush through millions of jellyfish, and visit a world where the closer you look, the more you see in these living underwater cities.

made with new macro—underwater cinematography, The Last Reef reveals an astonishing world rarely seen at this scale. From surprisingly colorful wormlike nudbranchs no bigger than you little finger, to  giant clams, anemones, and 'Christmas tree' worms, the film presents an unprecedented vision of the intriguing creatures that participate in altering the geology of our planet.  Showtimes:  10:45 am, 11:15 am, 11:45 am, 12:15 pm, and 1:15 pm.']]]}